java-server:
	java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8082 --public --languageModel /home/karin/_master-thesis/dev/english-bot/language-tool/ngrams-en-20150817

latex-lt-server:
	java -cp languagetool-server.jar org.languagetool.server.HTTPServer --port 8082 --public --languageModel /home/karin/_master-thesis/dev/english-bot/language-tool/ngrams-de-20150819

